name: prep
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  # The following adds local file reading and writing functionality
  path_provider: ^0.5.0+1

  # The following is an alternative to WebView (official flutter tool) for viewing web content
  flutter_html: ^0.9.4

  # The following adds the functionality to open URLs
  url_launcher: ^5.0.2
  validators: ^2.0.0+1

  # The following adds Firebase Cloud Messaging (Push Notifications).
  firebase_messaging: ^4.0.0+1

  # The following adds a mocking library for integration testing
  mockito: ^4.0.0

  # The following adds Firebase Cloud Database Firestore.
  cloud_firestore: ^0.9.5+2

  # The following adds staggered grid views (dynamically sized grid views)
  flutter_staggered_grid_view: ^0.2.7

  #The following adds image cashing and error handling
  cached_network_image: ^0.7.0
  flutter_cache_manager: ^0.3.2

  #The following generated the apps launcher icons
  flutter_launcher_icons: "^0.7.0"

  # The following adds encryption
  pointycastle: ^1.0.1
  hex: ^0.1.2

  flutter:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android/prep_icon_android.png"
  image_path_ios: "assets/icon/ios/prep_icon_ios.png"
  adaptive_icon_background: "#F7F7F7"
  adaptive_icon_foreground: "assets/icon/android/adaptive/prep_icon_android_adaptive.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  matcher: ^0.12.3+1
  coverage: ^0.12.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/recipes/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
